[package]
name = "axum-tower-lesson"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
axum = "0.7.5"
tower ={ version = "*", features = ["full"]}
http = "1.1.0"
